[package]
name = "MsgProto"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcode = "0.6.4"
thiserror = "2.0.11"

[[bin]]
name = "client"
path = "src/client_main.rs"

[[bin]]
name = "server"
path = "src/server_main.rs"
